# Generated by Django 5.2.17 on 2026-10-05 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cambio", "0002_initial"),
        ("organizaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "caja",
                "verbose_name_plural": "cajas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Concepto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                (
                    "caja",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = sirve para cualquier caja.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conceptos",
                        to="finanzas.caja",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "padre",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional. Ej: «Luz» y «Agua» agrupados en «Servicios». Solo dos niveles.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hijos",
                        to="finanzas.concepto",
                        verbose_name="agrupado en",
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto",
                "verbose_name_plural": "conceptos",
                "ordering": ["tipo", "padre__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cuenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Efectivo USD, Banesco, Pago móvil.",
                        max_length=80,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("efectivo", "Efectivo"), ("banco", "Banco")],
                        default="efectivo",
                        max_length=10,
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")],
                        help_text="La moneda en la que está el dinero. No se puede cambiar después del primer movimiento.",
                        max_length=3,
                    ),
                ),
                ("banco", models.CharField(blank=True, max_length=80)),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Lo que había en la cuenta antes de empezar a usar Arca, en su moneda.",
                        max_digits=18,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuentas",
                        to="finanzas.caja",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuenta",
                "verbose_name_plural": "cuentas",
                "ordering": ["caja__nombre", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "numero_vale",
                    models.PositiveIntegerField(
                        editable=False, verbose_name="vale n.º"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                (
                    "tercero",
                    models.CharField(
                        blank=True,
                        help_text="Proveedor, donante u otra persona externa.",
                        max_length=120,
                    ),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="N.º de transferencia, pago móvil o factura.",
                        max_length=60,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("registrado", "Por aprobar"),
                            ("confirmado", "Confirmado"),
                            ("anulado", "Anulado"),
                        ],
                        default="confirmado",
                        max_length=12,
                    ),
                ),
                (
                    "uuid_cliente",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "motivo_anulacion",
                    models.TextField(blank=True, verbose_name="motivo de la anulación"),
                ),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="finanzas.caja",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="finanzas.concepto",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="finanzas.cuenta",
                    ),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="organizaciones.ejercicio",
                    ),
                ),
                (
                    "miembro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="organizaciones.membresia",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="cambio.tasacambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento",
                "verbose_name_plural": "movimientos",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="caja",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"), name="caja_unica_por_organizacion"
            ),
        ),
        migrations.AddConstraint(
            model_name="concepto",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "tipo", "nombre"),
                name="concepto_unico_por_organizacion_y_tipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cuenta",
            constraint=models.UniqueConstraint(
                fields=("caja", "nombre"), name="cuenta_unica_por_caja"
            ),
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(
                fields=["organizacion", "fecha"], name="finanzas_mo_organiz_37f3b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimiento",
            index=models.Index(
                fields=["cuenta", "estado"], name="finanzas_mo_cuenta__631517_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="movimiento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("uuid_cliente__isnull", False)),
                fields=("organizacion", "uuid_cliente"),
                name="movimiento_uuid_cliente_unico",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimiento",
            constraint=models.UniqueConstraint(
                fields=("caja", "ejercicio", "numero_vale"),
                name="vale_unico_por_caja_y_ejercicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimiento",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto__gt", 0)), name="movimiento_monto_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="movimiento",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("concepto__isnull", False),
                    models.Q(("descripcion", ""), _negated=True),
                    _connector="OR",
                ),
                name="movimiento_concepto_o_descripcion",
            ),
        ),
    ]
