# Generated by Django 5.2.17 on 2026-10-05 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
        ("organizaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Traslado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("monto_origen", models.DecimalField(decimal_places=4, max_digits=18)),
                ("monto_destino", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=60)),
                (
                    "estado",
                    models.CharField(
                        choices=[("confirmado", "Confirmado"), ("anulado", "Anulado")],
                        default="confirmado",
                        max_length=12,
                    ),
                ),
                (
                    "uuid_cliente",
                    models.UUIDField(blank=True, editable=False, null=True),
                ),
                (
                    "motivo_anulacion",
                    models.TextField(blank=True, verbose_name="motivo de la anulación"),
                ),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traslados_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cuenta_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traslados_entrantes",
                        to="finanzas.cuenta",
                    ),
                ),
                (
                    "cuenta_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traslados_salientes",
                        to="finanzas.cuenta",
                    ),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traslados",
                        to="organizaciones.ejercicio",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="traslados_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "traslado",
                "verbose_name_plural": "traslados",
                "ordering": ["-fecha", "-id"],
                "indexes": [
                    models.Index(
                        fields=["organizacion", "fecha"],
                        name="finanzas_tr_organiz_b1daa8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("uuid_cliente__isnull", False)),
                        fields=("organizacion", "uuid_cliente"),
                        name="traslado_uuid_cliente_unico",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("monto_origen__gt", 0), ("monto_destino__gt", 0)
                        ),
                        name="traslado_montos_positivos",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cuenta_origen", models.F("cuenta_destino")), _negated=True
                        ),
                        name="traslado_cuentas_distintas",
                    ),
                ],
            },
        ),
    ]
