# Generated by Django 5.2.17 on 2026-10-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0002_traslado"),
        ("organizaciones", "0002_miembros_sin_usuario_y_ver_reportes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuotaMiembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="monto mensual"
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "Dólares"), ("VES", "Bolívares")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "vigente_desde",
                    models.DateField(help_text="Se cuenta desde el mes de esta fecha."),
                ),
                (
                    "vigente_hasta",
                    models.DateField(
                        blank=True, help_text="Vacío = sigue vigente.", null=True
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                (
                    "concepto",
                    models.ForeignKey(
                        help_text="El concepto de ingreso con el que se registran sus pagos.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuotas",
                        to="finanzas.concepto",
                    ),
                ),
                (
                    "membresia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cuotas",
                        to="organizaciones.membresia",
                        verbose_name="miembro",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "cuota de miembro",
                "verbose_name_plural": "cuotas de miembros",
                "ordering": ["membresia__nombre_visible", "concepto__nombre"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("monto__gt", 0)),
                        name="cuota_monto_positivo",
                    ),
                    models.UniqueConstraint(
                        fields=("membresia", "concepto", "vigente_desde"),
                        name="cuota_unica_por_inicio",
                    ),
                ],
            },
        ),
    ]
