# Generated by Django 5.2.17 on 2026-10-06 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_cuotamiembro"),
        ("organizaciones", "0003_suscripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Arqueo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "saldo_sistema",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=18,
                        verbose_name="saldo según el sistema",
                    ),
                ),
                (
                    "contado",
                    models.DecimalField(
                        decimal_places=4, max_digits=18, verbose_name="contado"
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "ajuste",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arqueo_ajustado",
                        to="finanzas.movimiento",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arqueos",
                        to="finanzas.cuenta",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "realizado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="arqueos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "arqueo",
                "verbose_name_plural": "arqueos",
                "ordering": ["-fecha", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Anticipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "tercero",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="otra persona"
                    ),
                ),
                ("motivo", models.CharField(max_length=200, verbose_name="para qué")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Por rendir"),
                            ("rendido", "Rendido"),
                            ("anulado", "Anulado"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "fecha_rendicion",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de rendición"
                    ),
                ),
                (
                    "gastado",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anticipos",
                        to="finanzas.cuenta",
                    ),
                ),
                (
                    "entrega",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anticipo_entregado",
                        to="finanzas.movimiento",
                    ),
                ),
                (
                    "entregado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anticipos_entregados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gastos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="anticipos_rendidos",
                        to="finanzas.movimiento",
                    ),
                ),
                (
                    "miembro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anticipos",
                        to="organizaciones.membresia",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "anticipo",
                "verbose_name_plural": "anticipos",
                "ordering": ["-fecha", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("monto__gt", 0)),
                        name="anticipo_monto_positivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("miembro__isnull", False),
                            models.Q(("tercero", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="anticipo_con_responsable",
                    ),
                ],
            },
        ),
    ]
