# Generated by Django 5.2.17 on 2026-10-06 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizaciones", "0003_suscripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaArticulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clase",
                    models.CharField(
                        choices=[("bien", "Bien"), ("consumible", "Consumible")],
                        default="bien",
                        max_length=12,
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: serial, etiqueta o código propio.",
                        max_length=40,
                        verbose_name="código",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        default="unidad",
                        help_text="Cómo se cuenta: unidad, kg, litro, caja…",
                        max_length=20,
                    ),
                ),
                (
                    "minimo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Solo consumibles: por debajo de esta cantidad total, avisa.",
                        max_digits=12,
                        null=True,
                        verbose_name="mínimo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("bueno", "Bueno"),
                            ("regular", "Regular"),
                            ("malo", "Malo"),
                        ],
                        default="bueno",
                        help_text="Solo bienes.",
                        max_length=10,
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Opcional. Sirve para saber cuánto vale lo que hay; no toca el libro de caja.",
                        max_digits=18,
                        null=True,
                        verbose_name="valor por unidad",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "Dólares"), ("VES", "Bolívares")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: el miembro que lo tiene a su cargo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos_a_cargo",
                        to="organizaciones.membresia",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="articulos",
                        to="inventario.categoriaarticulo",
                        verbose_name="categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "artículo",
                "verbose_name_plural": "artículos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "ubicación",
                "verbose_name_plural": "ubicaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("traslado", "Traslado"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("inicial", "Existencia inicial"),
                            ("compra", "Compra"),
                            ("donacion", "Donación recibida"),
                            ("consumo", "Consumo / uso"),
                            ("entrega", "Entrega o donación a terceros"),
                            ("baja", "Baja por daño o desuso"),
                            ("perdida", "Pérdida"),
                            ("ajuste", "Ajuste por conteo"),
                            ("traslado", "Cambio de ubicación"),
                        ],
                        max_length=12,
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                ("nota", models.CharField(blank=True, max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("anulado", models.BooleanField(default=False)),
                (
                    "motivo_anulacion",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="motivo de la anulación",
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anulaciones_inventario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventario.articulo",
                        verbose_name="artículo",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_inventario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entradas",
                        to="inventario.ubicacion",
                        verbose_name="entra a",
                    ),
                ),
                (
                    "origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salidas",
                        to="inventario.ubicacion",
                        verbose_name="sale de",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de inventario",
                "verbose_name_plural": "movimientos de inventario",
                "ordering": ["-fecha", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="categoriaarticulo",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"),
                name="categoria_articulo_unica_por_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="articulo",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"),
                name="articulo_unico_por_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="articulo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimo__isnull", True), ("minimo__gte", 0), _connector="OR"
                ),
                name="articulo_minimo_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="articulo",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valor_unitario__isnull", True),
                    ("valor_unitario__gte", 0),
                    _connector="OR",
                ),
                name="articulo_valor_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="ubicacion",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"),
                name="ubicacion_unica_por_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="inventario_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="movimientoinventario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destino__isnull", False),
                        ("origen__isnull", True),
                        ("tipo", "entrada"),
                    ),
                    models.Q(
                        ("destino__isnull", True),
                        ("origen__isnull", False),
                        ("tipo", "salida"),
                    ),
                    models.Q(
                        ("destino__isnull", False),
                        ("origen__isnull", False),
                        ("tipo", "traslado"),
                        models.Q(("origen", models.F("destino")), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="inventario_ubicaciones_segun_tipo",
            ),
        ),
    ]
