# Generated by Django 5.2.17 on 2026-10-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                (
                    "rif",
                    models.CharField(blank=True, max_length=20, verbose_name="RIF"),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="dirección")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo"
                    ),
                ),
                (
                    "moneda_base",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")],
                        default="USD",
                        help_text="Moneda en la que se muestran primero los saldos y se arman los presupuestos.",
                        max_length=3,
                    ),
                ),
                (
                    "requiere_aprobacion_egresos",
                    models.BooleanField(
                        default=False,
                        help_text="Si está encendido, un egreso registrado queda pendiente hasta que el director o un administrador lo apruebe.",
                        verbose_name="requiere aprobación de egresos",
                    ),
                ),
                (
                    "director_ve_cuentas_personales",
                    models.BooleanField(
                        default=False,
                        help_text="Lo decide el superadmin de la plataforma, no la organización. Apagado: el director solo ve cuánto asignó a cada miembro. Encendido: ve además sus saldos y movimientos personales, en solo lectura. Cada cambio queda en la bitácora.",
                        verbose_name="el director ve las cuentas personales",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Apagada, nadie de la organización puede entrar.",
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "organización",
                "verbose_name_plural": "organizaciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoMiembro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60)),
                (
                    "puede_registrar_ingresos",
                    models.BooleanField(
                        default=False, verbose_name="registrar ingresos"
                    ),
                ),
                (
                    "puede_registrar_egresos",
                    models.BooleanField(
                        default=False, verbose_name="registrar egresos"
                    ),
                ),
                (
                    "puede_ver_presupuesto",
                    models.BooleanField(default=False, verbose_name="ver presupuesto"),
                ),
                (
                    "puede_ver_movimientos",
                    models.BooleanField(default=False, verbose_name="ver movimientos"),
                ),
                (
                    "puede_gestionar_inventario",
                    models.BooleanField(
                        default=False, verbose_name="gestionar inventario"
                    ),
                ),
                (
                    "tiene_cuenta_personal",
                    models.BooleanField(default=True, verbose_name="cuenta personal"),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de miembro",
                "verbose_name_plural": "tipos de miembro",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Membresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "es_dueno",
                    models.BooleanField(
                        default=False, verbose_name="es el director (dueño)"
                    ),
                ),
                (
                    "es_administrador",
                    models.BooleanField(default=False, verbose_name="es administrador"),
                ),
                (
                    "nombre_visible",
                    models.CharField(
                        blank=True,
                        help_text="Cómo aparece esta persona dentro de la organización. Vacío: su nombre de usuario.",
                        max_length=120,
                    ),
                ),
                ("activa", models.BooleanField(default=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membresias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Obligatorio salvo para el director y los administradores.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membresias",
                        to="organizaciones.tipomiembro",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía",
                "verbose_name_plural": "membresías",
                "ordering": [
                    "-es_dueno",
                    "-es_administrador",
                    "nombre_visible",
                    "user__username",
                ],
            },
        ),
        migrations.CreateModel(
            name="Ejercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(help_text="Ej: 2026", max_length=30)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activo", models.BooleanField(default=False)),
                ("cerrado", models.BooleanField(default=False)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ejercicios_cerrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejercicio",
                "verbose_name_plural": "ejercicios",
                "ordering": ["-fecha_inicio"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organizacion", "nombre"),
                        name="ejercicio_unico_por_organizacion",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("activo", True)),
                        fields=("organizacion",),
                        name="un_solo_ejercicio_activo_por_organizacion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fecha_inicio__lt", models.F("fecha_fin"))),
                        name="ejercicio_inicio_antes_de_fin",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tipomiembro",
            constraint=models.UniqueConstraint(
                fields=("organizacion", "nombre"), name="tipo_unico_por_organizacion"
            ),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.UniqueConstraint(
                fields=("user", "organizacion"),
                name="una_membresia_por_usuario_y_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.UniqueConstraint(
                condition=models.Q(("es_dueno", True)),
                fields=("organizacion",),
                name="un_solo_dueno_por_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("es_dueno", True),
                    ("es_administrador", True),
                    ("tipo__isnull", False),
                    _connector="OR",
                ),
                name="miembro_comun_con_tipo",
            ),
        ),
    ]
