# Generated by Django 5.2.17 on 2026-10-05 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copiar_permiso(apps, schema_editor):
    """Hasta ahora los reportes iban con «ver movimientos»: quien ya los veía, los sigue viendo."""
    TipoMiembro = apps.get_model("organizaciones", "TipoMiembro")
    TipoMiembro.objects.filter(puede_ver_movimientos=True).update(puede_ver_reportes=True)


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tipomiembro",
            name="puede_ver_reportes",
            field=models.BooleanField(default=False, verbose_name="ver reportes"),
        ),
        migrations.RunPython(copiar_permiso, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="membresia",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membresias",
                to=settings.AUTH_USER_MODEL,
                verbose_name="usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="membresia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    models.Q(
                        models.Q(("nombre_visible", ""), _negated=True),
                        ("es_dueno", False),
                        ("es_administrador", False),
                    ),
                    _connector="OR",
                ),
                name="miembro_sin_usuario_con_nombre_y_sin_mando",
            ),
        ),
    ]
