# Generated by Django 5.2.17 on 2026-10-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0002_miembros_sin_usuario_y_ver_reportes"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="activa_hasta",
            field=models.DateField(
                blank=True,
                help_text="Vacío = sin vencimiento. Pasada la fecha, nadie entra.",
                null=True,
                verbose_name="activa hasta",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="limite_usuarios",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Vacío = sin límite. Los miembros sin acceso al sistema no cuentan.",
                null=True,
                verbose_name="límite de usuarios con acceso",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="notas",
            field=models.TextField(
                blank=True,
                help_text="Solo las ve la plataforma.",
                verbose_name="notas internas",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="plan",
            field=models.CharField(
                choices=[("prueba", "Prueba"), ("basico", "Básico"), ("pro", "Pro")],
                default="prueba",
                max_length=10,
            ),
        ),
    ]
