# Generated by Django 5.2.17 on 2026-10-05 19:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("login_fallido", "Inicio de sesión fallido"),
                            ("cambiar_clave", "Cambio de contraseña"),
                            ("cargar_tasa", "Carga de tasa de cambio"),
                            ("editar_tasa", "Corrección de tasa de cambio"),
                            ("crear_organizacion", "Alta de organización"),
                            (
                                "editar_organizacion",
                                "Edición de datos de la organización",
                            ),
                            (
                                "visibilidad_cuentas",
                                "Cambio de visibilidad de cuentas personales",
                            ),
                            ("crear_tipo", "Creación de tipo de miembro"),
                            ("editar_tipo", "Edición de tipo de miembro"),
                            ("eliminar_tipo", "Eliminación de tipo de miembro"),
                            ("crear_miembro", "Alta de miembro"),
                            ("editar_miembro", "Edición de miembro"),
                            ("activar_miembro", "Activación de miembro"),
                            ("desactivar_miembro", "Desactivación de miembro"),
                            ("restablecer_clave", "Restablecimiento de contraseña"),
                            ("crear_ejercicio", "Creación de ejercicio"),
                            ("activar_ejercicio", "Activación de ejercicio"),
                            ("cerrar_ejercicio", "Cierre de ejercicio"),
                        ],
                        max_length=30,
                    ),
                ),
                ("modelo", models.CharField(blank=True, max_length=60)),
                ("objeto_id", models.CharField(blank=True, max_length=64)),
                ("descripcion", models.TextField(blank=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "bitácora de auditoría",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "debe_cambiar_clave",
                    models.BooleanField(
                        default=False,
                        help_text="Se enciende al crear el usuario o restablecer su clave con una temporal; se apaga cuando la cambia. Mientras esté encendido no puede usar el sistema.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
