# Generated by Django 5.2.17 on 2026-10-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("organizaciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroauditoria",
            name="organizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="registros_auditoria",
                to="organizaciones.organizacion",
            ),
        ),
        migrations.AddField(
            model_name="registroauditoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="registroauditoria",
            index=models.Index(
                fields=["organizacion", "-fecha"], name="core_regist_organiz_c824cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroauditoria",
            index=models.Index(
                fields=["modelo", "objeto_id"], name="core_regist_modelo_a44527_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroauditoria",
            index=models.Index(
                fields=["usuario", "fecha"], name="core_regist_usuario_ae64b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroauditoria",
            index=models.Index(
                fields=["accion", "fecha"], name="core_regist_accion_f40298_idx"
            ),
        ),
    ]
