# Generated by Django 5.2.17 on 2026-10-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_registroauditoria_accion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("login_fallido", "Inicio de sesión fallido"),
                    ("cambiar_clave", "Cambio de contraseña"),
                    ("cargar_tasa", "Carga de tasa de cambio"),
                    ("editar_tasa", "Corrección de tasa de cambio"),
                    ("crear_organizacion", "Alta de organización"),
                    ("editar_organizacion", "Edición de datos de la organización"),
                    (
                        "visibilidad_cuentas",
                        "Cambio de visibilidad de cuentas personales",
                    ),
                    ("crear_tipo", "Creación de tipo de miembro"),
                    ("editar_tipo", "Edición de tipo de miembro"),
                    ("eliminar_tipo", "Eliminación de tipo de miembro"),
                    ("crear_miembro", "Alta de miembro"),
                    ("editar_miembro", "Edición de miembro"),
                    ("activar_miembro", "Activación de miembro"),
                    ("desactivar_miembro", "Desactivación de miembro"),
                    ("restablecer_clave", "Restablecimiento de contraseña"),
                    ("crear_ejercicio", "Creación de ejercicio"),
                    ("activar_ejercicio", "Activación de ejercicio"),
                    ("cerrar_ejercicio", "Cierre de ejercicio"),
                    ("crear_caja", "Creación de caja"),
                    ("editar_caja", "Edición de caja"),
                    ("crear_cuenta", "Creación de cuenta"),
                    ("editar_cuenta", "Edición de cuenta"),
                    ("ajustar_saldo_cuenta", "Ajuste de saldo inicial de cuenta"),
                    ("crear_concepto", "Creación de concepto"),
                    ("editar_concepto", "Edición de concepto"),
                    ("registrar_movimiento", "Registro de ingreso o egreso"),
                    ("aprobar_movimiento", "Aprobación de egreso"),
                    ("anular_movimiento", "Anulación de movimiento"),
                    ("registrar_traslado", "Traslado entre cuentas"),
                    ("anular_traslado", "Anulación de traslado"),
                ],
                max_length=30,
            ),
        ),
    ]
