# Generated by Django 5.2.17 on 2026-10-06 00:24

import core.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


def repartir(apps, schema_editor):
    """Cada usuario queda como cuenta de UNA organización: la de su membresía
    principal (donde es director; si no, la primera activa). Los superusuarios
    y quien no tenga membresía quedan como cuentas de plataforma. Si alguien
    pertenecía a varias, sus otras membresías se desactivan (no se borran).
    Los nombres pasan a minúsculas, sin repetirse dentro de la organización."""
    Usuario = apps.get_model("core", "Usuario")
    Membresia = apps.get_model("organizaciones", "Membresia")
    usados = set()
    for u in Usuario.objects.order_by("pk"):
        organizacion_id = None
        if not u.is_superuser:
            m = Membresia.objects.filter(user_id=u.pk).order_by("-es_dueno", "-activa", "pk").first()
            if m is not None:
                organizacion_id = m.organizacion_id
                Membresia.objects.filter(user_id=u.pk).exclude(organizacion_id=organizacion_id).update(activa=False)
        base = (u.username or "").strip().lower() or f"usuario{u.pk}"
        nombre, n = base, 2
        while (organizacion_id, nombre) in usados:
            nombre, n = f"{base}{n}", n + 1
        usados.add((organizacion_id, nombre))
        u.username, u.organizacion_cuenta_id = nombre[:150], organizacion_id
        u.save(update_fields=["username", "organizacion_cuenta"])


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0008_alter_registroauditoria_accion"),
        ("organizaciones", "0003_suscripcion"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", core.models.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name="usuario",
            name="organizacion_cuenta",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío = cuenta de plataforma (soporte de Arca).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios_propios",
                to="organizaciones.organizacion",
                verbose_name="organización de la cuenta",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(
                help_text="Letras, números y . _ - @ (sin espacios). Se guarda en minúsculas.",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="usuario",
            ),
        ),
        migrations.RunPython(repartir, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                fields=("organizacion_cuenta", "username"),
                name="usuario_unico_por_organizacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="usuario",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion_cuenta__isnull", True)),
                fields=("username",),
                name="usuario_plataforma_unico",
            ),
        ),
    ]
