# Generated by Django 5.2.17 on 2026-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_usuarios_por_organizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("login_fallido", "Inicio de sesión fallido"),
                    ("cambiar_clave", "Cambio de contraseña"),
                    ("cargar_tasa", "Carga de tasa de cambio"),
                    ("editar_tasa", "Corrección de tasa de cambio"),
                    ("crear_organizacion", "Alta de organización"),
                    ("editar_organizacion", "Edición de datos de la organización"),
                    (
                        "visibilidad_cuentas",
                        "Cambio de visibilidad de cuentas personales",
                    ),
                    ("crear_tipo", "Creación de tipo de miembro"),
                    ("editar_tipo", "Edición de tipo de miembro"),
                    ("eliminar_tipo", "Eliminación de tipo de miembro"),
                    ("crear_miembro", "Alta de miembro"),
                    ("editar_miembro", "Edición de miembro"),
                    ("activar_miembro", "Activación de miembro"),
                    ("desactivar_miembro", "Desactivación de miembro"),
                    ("restablecer_clave", "Restablecimiento de contraseña"),
                    ("dar_acceso", "Acceso al sistema para un miembro"),
                    ("crear_ejercicio", "Creación de ejercicio"),
                    ("activar_ejercicio", "Activación de ejercicio"),
                    ("cerrar_ejercicio", "Cierre de ejercicio"),
                    ("crear_caja", "Creación de caja"),
                    ("editar_caja", "Edición de caja"),
                    ("crear_cuenta", "Creación de cuenta"),
                    ("editar_cuenta", "Edición de cuenta"),
                    ("ajustar_saldo_cuenta", "Ajuste de saldo inicial de cuenta"),
                    ("crear_concepto", "Creación de concepto"),
                    ("editar_concepto", "Edición de concepto"),
                    ("registrar_movimiento", "Registro de ingreso o egreso"),
                    ("aprobar_movimiento", "Aprobación de egreso"),
                    ("anular_movimiento", "Anulación de movimiento"),
                    ("registrar_traslado", "Traslado entre cuentas"),
                    ("anular_traslado", "Anulación de traslado"),
                    ("crear_presupuesto", "Creación de presupuesto"),
                    ("editar_presupuesto", "Edición de presupuesto"),
                    ("aprobar_presupuesto", "Aprobación de presupuesto"),
                    ("reabrir_presupuesto", "Reapertura de presupuesto"),
                    ("eliminar_presupuesto", "Eliminación de presupuesto"),
                    ("emitir_reporte", "Emisión de reporte"),
                    ("crear_cuota", "Creación de cuota"),
                    ("editar_cuota", "Edición de cuota"),
                    ("asignar", "Asignación a un miembro"),
                    ("crear_articulo", "Alta de artículo de inventario"),
                    ("editar_articulo", "Edición de artículo de inventario"),
                    ("mover_inventario", "Movimiento de inventario"),
                    ("anular_inventario", "Anulación de movimiento de inventario"),
                    ("editar_suscripcion", "Cambio de suscripción (plataforma)"),
                    (
                        "ver_cuenta_personal",
                        "Consulta de la cuenta personal de un miembro",
                    ),
                ],
                max_length=30,
            ),
        ),
    ]
