# Generated by Django 5.2.17 on 2026-10-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cambio", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltasacambio",
            name="cargada_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltasacambio",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasacambio",
            name="cargada_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasas_cargadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tasacambio",
            index=models.Index(
                fields=["fuente", "-fecha"], name="cambio_tasa_fuente_057269_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasacambio",
            constraint=models.UniqueConstraint(
                fields=("fecha", "fuente"), name="tasa_unica_por_fecha_y_fuente"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasacambio",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)), name="tasa_valor_positivo"
            ),
        ),
    ]
