# Generated by Django 5.2.17 on 2026-10-07 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cambio", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltasacambio",
            name="cargada_por",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Vacío = la cargó la consulta automática al BCV.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tasacambio",
            name="cargada_por",
            field=models.ForeignKey(
                blank=True,
                help_text="Vacío = la cargó la consulta automática al BCV.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasas_cargadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
