# Generated by Django 5.2.17 on 2026-10-07 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cambio", "0003_tasa_automatica"),
        ("organizaciones", "0003_suscripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tasacambio",
            name="tasa_unica_por_fecha_y_fuente",
        ),
        migrations.AddField(
            model_name="historicaltasacambio",
            name="organizacion",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizaciones.organizacion",
                verbose_name="organización",
            ),
        ),
        migrations.AddField(
            model_name="tasacambio",
            name="organizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasas_propias",
                to="organizaciones.organizacion",
                verbose_name="organización",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasacambio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", True)),
                fields=("fecha", "fuente"),
                name="tasa_unica_por_fecha_y_fuente",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasacambio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organizacion__isnull", False)),
                fields=("organizacion", "fecha"),
                name="tasa_propia_unica_por_dia",
            ),
        ),
    ]
