# Generated by Django 5.2.17 on 2026-10-05 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finanzas", "0002_traslado"),
        ("organizaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[("USD", "Dólares"), ("VES", "Bolívares")],
                        default="USD",
                        help_text="La moneda en la que se planifica. Lo ejecutado se compara en esta misma moneda.",
                        max_length=3,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("borrador", "Borrador"), ("aprobado", "Aprobado")],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                ("nota", models.TextField(blank=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos_aprobados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="finanzas.caja",
                    ),
                ),
                (
                    "ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presupuestos",
                        to="organizaciones.ejercicio",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "presupuesto",
                "verbose_name_plural": "presupuestos",
                "ordering": ["-ejercicio__fecha_inicio", "caja__nombre"],
            },
        ),
        migrations.CreateModel(
            name="PartidaPresupuestaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_mensual",
                    models.DecimalField(decimal_places=4, default=0, max_digits=18),
                ),
                (
                    "requiere_solicitud",
                    models.BooleanField(
                        default=False,
                        help_text="Partidas que no tienen un monto fijo y se solicitan indicando el monto exacto.",
                        verbose_name="se pide con antelación",
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="partidas",
                        to="finanzas.concepto",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas",
                        to="presupuestos.presupuesto",
                    ),
                ),
            ],
            options={
                "verbose_name": "partida presupuestaria",
                "verbose_name_plural": "partidas presupuestarias",
                "ordering": ["concepto__tipo", "concepto__nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="presupuesto",
            constraint=models.UniqueConstraint(
                fields=("caja", "ejercicio"), name="un_presupuesto_por_caja_y_ejercicio"
            ),
        ),
        migrations.AddConstraint(
            model_name="partidapresupuestaria",
            constraint=models.UniqueConstraint(
                fields=("presupuesto", "concepto"), name="una_partida_por_concepto"
            ),
        ),
        migrations.AddConstraint(
            model_name="partidapresupuestaria",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto_mensual__gte", 0)),
                name="partida_monto_no_negativo",
            ),
        ),
    ]
