# Generated by Django 5.2.17 on 2026-10-05 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cambio", "0002_initial"),
        ("finanzas", "0003_cuotamiembro"),
        ("organizaciones", "0002_miembros_sin_usuario_y_ver_reportes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                (
                    "membresia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos_personales",
                        to="organizaciones.membresia",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
            ],
            options={
                "verbose_name": "concepto personal",
                "verbose_name_plural": "conceptos personales",
                "ordering": ["tipo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoPersonal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "moneda",
                    models.CharField(
                        choices=[("VES", "Bolívares"), ("USD", "Dólares")], max_length=3
                    ),
                ),
                (
                    "tasa_aplicada",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_ves",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "monto_usd",
                    models.DecimalField(
                        decimal_places=4, editable=False, max_digits=18
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ingreso", "Ingreso"), ("egreso", "Egreso")],
                        max_length=10,
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descripción"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="personal.conceptopersonal",
                    ),
                ),
                (
                    "membresia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_personales",
                        to="organizaciones.membresia",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="organizaciones.organizacion",
                        verbose_name="organización",
                    ),
                ),
                (
                    "origen",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignacion_personal",
                        to="finanzas.movimiento",
                    ),
                ),
                (
                    "tasa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_personales",
                        to="cambio.tasacambio",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento personal",
                "verbose_name_plural": "movimientos personales",
                "ordering": ["-fecha", "-id"],
                "indexes": [
                    models.Index(
                        fields=["membresia", "fecha"],
                        name="personal_mo_membres_9d9ca6_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("monto__gt", 0)),
                        name="personal_monto_positivo",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("concepto__isnull", False),
                            models.Q(("descripcion", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="personal_concepto_o_descripcion",
                    ),
                ],
            },
        ),
    ]
